ProtalkAdminBundle:
    resource: "@ProtalkAdminBundle/Controller/"
    type:     annotation
    prefix:   /

ProtalkMediaBundle:
    resource: "@ProtalkMediaBundle/Controller/"
    type:     annotation
    prefix:   /

_home:
    pattern:  /
    defaults: { _controller: ProtalkMediaBundle:Home:index }

speaker_show:
    pattern: /speaker/{name}/{id}
    defaults: {_controller: ProtalkMediaBundle:Speaker:show }
    requirements:
        id:  \d+

get_speakers:
  pattern:  /media/{id}/speakers
  defaults: {_controller: ProtalkMediaBundle:Media:speakers}

contribute_new:
    pattern: /contribute/new
    defaults: {_controller: ProtalkMediaBundle:Contribution:new }

rate_media:
    pattern: /rate/{id}/{rating}
    defaults: {_controller: ProtalkMediaBundle:Media:rate }
    requirements:
        id:     \d+
        rating: \d+

comment_new:
    pattern: /comment/{media_id}
    defaults: {_controller: ProtalkMediaBundle:Comment:new }
    requirements:
        id:     \d+

ProtalkPageBundle:
    resource: "@ProtalkPageBundle/Controller/"
    type:     annotation
    prefix:   /page

page_show:
    pattern:  /page/{url}
    defaults: { _controller: ProtalkPageBundle:Page:index }

explore:
    pattern:  /explore
    defaults: { _controller: ProtalkMediaBundle:Explore:index }

search_results:
    pattern:  /result
    defaults: { _controller: ProtalkMediaBundle:Explore:result }

tag_search:
    pattern:  /tag/{id}
    defaults: { _controller: ProtalkMediaBundle:Explore:tag }

category_search:
    pattern:  /category/{id}
    defaults: { _controller: ProtalkMediaBundle:Explore:category }

speaker_search:
    pattern:  /search/speaker/{id}
    defaults: { _controller: ProtalkMediaBundle:Explore:speaker }

media_show:
    pattern:  /{slug}
    defaults: { _controller: ProtalkMediaBundle:Media:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
